cc_binary(
  name = "hello",
  srcs = ["hello.cc"],
  deps = ["@fmt"],
)

cc_binary(
  name = "fib",
  srcs = ["fib.cc"],
)

java_binary(
  name = "Main",
  srcs = ["Main.java"],
  main_class = "example.Main",
)
